#-*- coding: utf-8 -*-

##########################################################
# © 2013/2014 Daniel 'grindhold' Brendle with torservers.net
#
# This file is part of torcollect
#
# torcollect is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later
# version.
#
# torcollect is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with torcollect.
# If not, see http://www.gnu.org/licenses/.
###########################################################

import re
from pygal.style import Style

RE_XML_COMMENT = re.compile(r"<!--.*?-->")

class TorcollectStyle(Style):
    """ Defines a common style for the pygal-graphs used by torcollect
    """
    def __init__(self):
        Style.__init__(self)
        self.background = 'transparent'
        self.plot_background = 'transparent'
        self.colors = ('#aaff00', '#550055')
        self.foreground_dark = '#010101'

def clean_graph(xml):
    """ Strips unnecessary code off the svgs generated by pygal
    """
    xml = re.sub(RE_XML_COMMENT, "", xml)
    return xml.replace ("<?xml version='1.0' encoding='utf-8'?>","",1)


